name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        wasi_sdk_version:
        - major: 11
          minor: 0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SwiftWasm
      run: |
        sudo apt-get install \
          binutils \
          git \
          libc6-dev \
          libcurl4 \
          libedit2 \
          libgcc-5-dev \
          libpython2.7 \
          libsqlite3-0 \
          libstdc++-5-dev \
          libxml2 \
          pkg-config \
          tzdata \
          zlib1g-dev \
          libtinfo5
        wget https://github.com/swiftwasm/swift/releases/download/swift-wasm-5.3.0-RELEASE/swift-wasm-5.3.0-RELEASE-ubuntu20.04_x86_64.tar.gz
        sudo tar zxvf swift-wasm-5.3.0-RELEASE-ubuntu20.04_x86_64.tar.gz --directory / --strip-components=1
        sudo chmod -R o+r /usr/lib/swift
        ls -lah /usr/lib/swift
    - name: Build
      run: make build-linux
